### ISSUE TITLE
Error with Webpack task

### ISSUE THREAD

**Issue by dmackerman** [driftyco/ionic-gulp-tasks#3]
When using the latest `ionic 2.0.0-beta.24`, running `ionic serve`:

``` shell
Running 'serve:before' gulp task before serve
[10:11:10] Starting 'fonts'...
[10:11:10] Starting 'sass'...
[10:11:10] Finished 'fonts' after 54 ms
[10:11:11] Finished 'sass' after 610 ms
[10:11:11] Starting 'watch'...
[10:11:11] 'watch' errored after 12 ms
[10:11:11] SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at module.exports (/Users/dave/Sites/calamp-mobile-locate/node_modules/ionic-gulp-webpack-build/index.js:20:38)
    at Gulp.<anonymous> (/Users/dave/Sites/calamp-mobile-locate/gulpfile.js:37:12)
    at module.exports (/Users/dave/Sites/calamp-mobile-locate/node_modules/orchestrator/lib/runTask.js:34:7)
Proxy added: /forecast/ => https://api.forecast.io/forecast/086eaa44711f06f855c4b8759970fa6b
Running live reload server: http://localhost:35729
Watching: www/**/*, !www/lib/**/*
√ Running dev server:  http://localhost:8100
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

ionic $ 

```

**Comment by dmackerman** [comment]
Turns out I had a syntax error in my `webpack.config.js`. It'd be awesome if there was a graceful error handling, something maybe as simple as:

``` js
try {
    var webpackConfig = require(process.cwd() + '/webpack.config.js');
   // proceed
} catch (err) {
    console.log("There was an issue with your webpack.config file.");
}
```

**Comment by tlancina** [comment]
Should be done in https://github.com/driftyco/ionic-gulp-tasks/commit/26235f82de94e866a71bb4008a2ad3d2985e128c, thanks!
